### ISSUE TITLE
do not work on flatline rule?

### ISSUE THREAD

**Issue by fberrez** [0xSeb/elastalert_hour_range#5]
The module does not seem to work with a flatline rule.

# Situation

- I have the following rule:

```yaml
name: myFlatlineRule
description: sends alert when a flatline occured in my log
index: myIndex-*
type: flatline
timeframe:
  minutes: 5
threshold: 1
filter:
  - term:
      fields.metadata.code.keyword: 'MY_LOG_CODE'

realert:
  minutes: 1

start_time: '5:00' # 7:00 Europe/Paris
end_time: '20:00' # 22:00 Europe/Paris
drop_if: "outside"
```

When this is triggered, an alert is sent to my slack channel.

- With the logs (timezone: `Europe/Paris`):

<img width="752" alt="image" src="https://user-images.githubusercontent.com/25006376/121136640-2afdd700-c836-11eb-927a-6195c1d646a0.png">

We can see that a flatine exists between `00:10` and `05:00` (`Europe/Paris`).

- In my slack channel:

The first alert starts at `00:25` and the last one is sent at `05:01` (`Europe/Paris`).

# Expected behavior

No alert should be sent between `22:00` and `7:00` (`Europe/Paris`).
